/** @file */

#pragma once

#include "platform.h"

#define NP_CLANG_GOODIES_VERSION "0.5.1"
#define NP_CLANG_GOODIES_VERSION_W L"0.5.1"

#define NP_CLANG_GOODIES_VERSION_MAJOR 0
#define NP_CLANG_GOODIES_VERSION_MINOR 5
#define NP_CLANG_GOODIES_VERSION_PATCH 1
#define NP_CLANG_GOODIES_VERSION_EXTRA 0
