/** @file */

#pragma once

#include "platform.h"

#define NP_CLANG_GOODIES_VERSION "0.4.0"

#if defined(NP_PLATFORM_SUPPORTS_WCHAR_T)
	#define NP_CLANG_GOODIES_VERSION_W L"0.4.0"
#endif

#define NP_CLANG_GOODIES_VERSION_MAJOR 0
#define NP_CLANG_GOODIES_VERSION_MINOR 4
#define NP_CLANG_GOODIES_VERSION_PATCH 0
#define NP_CLANG_GOODIES_VERSION_EXTRA 0
