name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: cicd-docs
    steps:
      - name: Checkout Git submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build Doxygen documentation
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: 'docs/'
          doxyfile-path: 'Doxyfile'

      - name: Copy extra files
        run: |
          mkdir -p docs/html/docs/images
          cp docs/images/bug.png docs/html/docs/images/
          cp docs/images/chain.png docs/html/docs/images/
          cp docs/images/console.png docs/html/docs/images/
          cp docs/images/module.png docs/html/docs/images/
          cp docs/images/text.png docs/html/docs/images/
          cp docs/images/favicon.ico docs/html/
          cp docs/images/favicon.svg docs/html/

      - name: Deploy documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
